version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_gateway
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: gateway_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://gateway_user:gateway_pass@postgres:5432/payment_gateway
      PORT: 8000
      TEST_MODE: "true"
    depends_on:
      postgres:
        condition: service_healthy

  dashboard:
      build: ./frontend
      container_name: gateway_dashboard
      ports:
        - "3000:3000"
      # This command forces port 3000 and removes the conflict
      command: npm run dev -- --host 0.0.0.0 --port 3000
      stdin_open: true
      tty: true
      depends_on:
        - api


  checkout:
    build: ./checkout-page
    container_name: gateway_checkout
    ports:
      - "3001:3001"
    # This overrides the internal CMD to ensure port 3001 is strictly used
    command: npm run dev -- --host 0.0.0.0 --port 3001
    stdin_open: true
    tty: true
    depends_on:
      - api